apiVersion: v1
kind: Service
metadata:
  name: hverse-project04-svc

spec:
  type: NodePort
  selector:
    app: hverse-project04
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30084



