pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    docker build \
                    -f Project-06-Jenkins-CI/docker/Dockerfile \
                    -t adil503/hverse-jenkins:v2 \
                    Project-06-Jenkins-CI
                '''
            }
        }

        stage('Docker Test') {
            steps {
                sh 'docker images adil503/hverse-jenkins'
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        docker push adil503/hverse-jenkins:v2
                        docker logout
                    '''
                }
            }
        }
	stage('Deploy to Kubernetes') {
   	    steps {
		        sh '''
		            kubectl apply -f Project-06-Jenkins-CI/kubernetes/deployment.yaml
		            kubectl apply -f Project-06-Jenkins-CI/kubernetes/service.yaml
		            kubectl rollout status deployment/hverse-jenkins
		        '''
		    }
		}
    }
}
